// Generated by Xata Codegen 0.29.3. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "Users",
    columns: [
      { name: "email", type: "email", unique: true },
      { name: "name", type: "string", notNull: true, defaultValue: "user" },
      { name: "avatar", type: "string" },
      { name: "isGov", type: "bool", notNull: true, defaultValue: "false" },
    ],
    revLinks: [
      { column: "user", table: "Messages" },
      { column: "user", table: "SavedHouses" },
      { column: "user", table: "OAuth" },
      { column: "user", table: "Sessions" },
    ],
  },
  {
    name: "Messages",
    columns: [
      { name: "user", type: "link", link: { table: "Users" } },
      { name: "message", type: "text" },
      { name: "title", type: "string" },
      { name: "status", type: "string", notNull: true, defaultValue: "open" },
      { name: "lon", type: "float", defaultValue: "0" },
      { name: "lat", type: "float", defaultValue: "0" },
      { name: "category", type: "string", defaultValue: "Aucune" },
    ],
  },
  {
    name: "SavedHouses",
    columns: [
      { name: "user", type: "link", link: { table: "Users" } },
      { name: "address", type: "link", link: { table: "Addresses_old" } },
    ],
  },
  {
    name: "OAuth",
    columns: [
      {
        name: "provider",
        type: "string",
        notNull: true,
        defaultValue: "unknown",
      },
      { name: "user", type: "link", link: { table: "Users" } },
      { name: "accountId", type: "string", unique: true },
    ],
  },
  {
    name: "Sessions",
    columns: [
      { name: "user", type: "link", link: { table: "Users" } },
      {
        name: "expiresAt",
        type: "datetime",
        notNull: true,
        defaultValue: "now",
      },
    ],
  },
  { name: "MapData", columns: [{ name: "numberOfTrees", type: "int" }] },
  {
    name: "Addresses_old",
    columns: [
      { name: "latitude", type: "float" },
      { name: "longitude", type: "float" },
      { name: "source_id", type: "int" },
      { name: "group_id", type: "int" },
      { name: "street_no", type: "string" },
      { name: "street", type: "string" },
      { name: "str_name", type: "string" },
      { name: "str_type", type: "string" },
      { name: "str_dir", type: "string" },
      { name: "unit", type: "string" },
      { name: "city", type: "string" },
      { name: "postal_code", type: "string" },
      { name: "full_addr", type: "string" },
      { name: "city_pcs", type: "string" },
      { name: "str_name_pcs", type: "string" },
      { name: "str_type_pcs", type: "string" },
      { name: "str_dir_pcs", type: "string" },
      { name: "csduid", type: "int" },
      { name: "csdname", type: "string" },
      { name: "pruid", type: "int" },
      { name: "provider", type: "string" },
    ],
    revLinks: [{ column: "address", table: "SavedHouses" }],
  },
  {
    name: "Locations",
    columns: [
      { name: "er_code", type: "string", notNull: true, defaultValue: " " },
      { name: "fed_name", type: "string", notNull: true, defaultValue: " " },
      { name: "er_name", type: "string", notNull: true, defaultValue: " " },
      { name: "latitude", type: "float", notNull: true, defaultValue: "0" },
      { name: "longitude", type: "float", notNull: true, defaultValue: "0" },
    ],
    revLinks: [{ column: "location", table: "Addresses" }],
  },
  {
    name: "MessagesStats",
    columns: [
      { name: "Year", type: "int", notNull: true, defaultValue: "0" },
      { name: "Month", type: "int", notNull: true, defaultValue: "0" },
      { name: "Category", type: "string", notNull: true, defaultValue: "" },
      { name: "Count", type: "int", notNull: true, defaultValue: "0" },
    ],
  },
  {
    name: "h3_hexes",
    columns: [
      { name: "polygon", type: "json" },
      { name: "resolution", type: "int" },
    ],
    revLinks: [{ column: "hex", table: "BusinessAnalysis" }],
  },
  {
    name: "Addresses",
    columns: [
      { name: "civic_no", type: "string", notNull: true, defaultValue: "" },
      {
        name: "civic_no_suffix",
        type: "string",
        notNull: true,
        defaultValue: "",
      },
      { name: "street_name", type: "string", notNull: true, defaultValue: "" },
      { name: "street_type", type: "string", notNull: true, defaultValue: "" },
      { name: "street_dir", type: "string", notNull: true, defaultValue: "" },
      { name: "mail_street_name", type: "string" },
      {
        name: "mail_street_type",
        type: "string",
        notNull: true,
        defaultValue: "",
      },
      {
        name: "mail_street_dir",
        type: "string",
        notNull: true,
        defaultValue: "",
      },
      {
        name: "mail_mun_name",
        type: "string",
        notNull: true,
        defaultValue: "",
      },
      { name: "mail_prov", type: "string", notNull: true, defaultValue: "" },
      {
        name: "mail_postal_code",
        type: "string",
        notNull: true,
        defaultValue: "",
      },
      { name: "mail_info", type: "string", notNull: true, defaultValue: "" },
      { name: "usage", type: "int", notNull: true, defaultValue: "4" },
      { name: "location", type: "link", link: { table: "Locations" } },
      {
        name: "civic_no_prefix",
        type: "string",
        notNull: true,
        defaultValue: "",
      },
    ],
  },
  {
    name: "BusinessAnalysis",
    columns: [
      { name: "entreprises", type: "json" },
      { name: "contained", type: "json" },
      { name: "neighborhoodscore", type: "float" },
      { name: "score", type: "float" },
      { name: "count", type: "int" },
      { name: "hex", type: "link", link: { table: "h3_hexes" }, unique: true },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Users = InferredTypes["Users"];
export type UsersRecord = Users & XataRecord;

export type Messages = InferredTypes["Messages"];
export type MessagesRecord = Messages & XataRecord;

export type SavedHouses = InferredTypes["SavedHouses"];
export type SavedHousesRecord = SavedHouses & XataRecord;

export type OAuth = InferredTypes["OAuth"];
export type OAuthRecord = OAuth & XataRecord;

export type Sessions = InferredTypes["Sessions"];
export type SessionsRecord = Sessions & XataRecord;

export type MapData = InferredTypes["MapData"];
export type MapDataRecord = MapData & XataRecord;

export type AddressesOld = InferredTypes["Addresses_old"];
export type AddressesOldRecord = AddressesOld & XataRecord;

export type Locations = InferredTypes["Locations"];
export type LocationsRecord = Locations & XataRecord;

export type MessagesStats = InferredTypes["MessagesStats"];
export type MessagesStatsRecord = MessagesStats & XataRecord;

export type H3Hexes = InferredTypes["h3_hexes"];
export type H3HexesRecord = H3Hexes & XataRecord;

export type Addresses = InferredTypes["Addresses"];
export type AddressesRecord = Addresses & XataRecord;

export type BusinessAnalysis = InferredTypes["BusinessAnalysis"];
export type BusinessAnalysisRecord = BusinessAnalysis & XataRecord;

export type DatabaseSchema = {
  Users: UsersRecord;
  Messages: MessagesRecord;
  SavedHouses: SavedHousesRecord;
  OAuth: OAuthRecord;
  Sessions: SessionsRecord;
  MapData: MapDataRecord;
  Addresses_old: AddressesOldRecord;
  Locations: LocationsRecord;
  MessagesStats: MessagesStatsRecord;
  h3_hexes: H3HexesRecord;
  Addresses: AddressesRecord;
  BusinessAnalysis: BusinessAnalysisRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL: "https://wolfgang-p564tb.us-east-1.xata.sh/db/InfoToit",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
