export const mois = [
    "Janvier",
    "Février",
    "Mars",
    "Avril",
    "Mai",
    "Juin",
    "Juillet",
    "Août",
    "Septembre",
    "Octobre",
    "Novembre",
    "Décembre",
];

export const messageStatuses = ["En cours", "Terminé"] as const;

export const messageCategories = [
    "Feux de circulation - Entretien",
    "IRP - Fermeture de rue",
    "Nid-de-poule",
    "Y-Eau - Divers",
    "Direction - Capital humain",
    "Gouvernement du Québec",
    "Collecte de résidus alimentaires",
    "Voirie - Divers",
    "Société paramunicipale",
    "Info-Remorquage",
    "Fermeture d'entrée d'eau",
    "Cour municipale",
    "Fermeture d'une conduite d'eau - Urgence",
    "Neige - Remorquage",
    "Opération déneigement",
    "Accès à l'information",
    "Z-Puisard",
    "Refoulement égout / Inondation Propriété privée",
    "Permis animalier",
    "Collecte de déchets",
    "Bureau d'arrondissement - Service à la clientèle",
    "Collecte des encombrants",
    "Installations culturelles - Entretien",
    "Permis de construction - rénovation",
    "Assermentation",
    "Collecte de résidus verts",
    "Débris sur la voie publique",
    "Intervention stationnement",
    "Manque d'eau",
    "Organisme divers",
    "Écocentre",
    "Direction d'arrondissement",
    "Subvention - Habitation - Service central",
    "Taxes foncières",
    "Entretien d'édifices municipaux",
    "IRP - Police",
    "Sports et loisirs - Activités",
    "*Autre - Greffe - Appel d'offres et soumission d'arrondissement",
    "Installations sportives intérieures - Entretien",
    "Collecte d'arbres de Noël",
    "Développement communautaire",
    "Pollution de l'air et de l'eau",
    "Grand parc",
    "*Parc - Activité hivernale",
    "Stationnement municipal",
    "Info-travaux - Arrondissement",
    "Direction - Évaluation",
    "Distribution au comptoir de bacs ou de sacs de récupération",
    "Distribution de circulaire",
    "Ouverture d'entrée d'eau",
    "Contrôle animalier",
    "Carte Accès Montréal",
    "Collecte des matières recyclables",
    "Gouvernement du Canada",
    "Certificat d'occupation commerciale ou professionnelle",
    "Bac montréalais (67 litres)",
    "Abri temporaire",
    "Installations sportives extérieures - Entretien",
    "Permis - Divers",
    "Rapport d'accident",
    "Collecte d'écran (ordinateur et téléviseur)",
    "Arbre - Divers",
    "Arbre tombé",
    "Éclairage existant - Entretien",
    "Culture - Activités",
    "Punaises de lit",
    "SRRR",
    "Égout - Crue des eaux",
    "Animal mort",
    "Événement métropolitain",
    "Fuite d'eau",
    "Entrée d'eau en plomb-Autre demande",
    "Collecte de branches d'arbre - Agrile du frêne",
    "Environnement - Divers",
    "Fichier des fournisseurs",
    "Branche tombée",
    "Dépôt illégal - Déchets",
    "*Neige - Divers",
    "Avis Occupant / Consommation",
    "Centre de services 311",
    "Animaux sauvages - Nuisance",
    "Surveillance et sécurité publique",
    "Réclamation",
    "Bruit",
    "Danger potentiel - Arbre",
    "Info-travaux - Service central",
    "Taxe d'eau",
    "Chaussée glissante",
    "Dépôt Illégal - Neige",
    "Communauté métropolitaine de Montréal",
    "Parc - Propreté",
    "IRP - Mesure d'urgence",
    "Parc - Divers",
    "Soutien Carte Info-Neige",
    "Carte Info-Neige",
    "Y-Égout - Divers",
    "Sécurité incendie - Thèmes administratifs",
    "Finances - Divers",
    "*Jardin botanique",
    "Urbanisme",
    "Arbre - Abattage illégal privé",
    "Pesticide",
    "Trottoir glissant",
    "Occupation du domaine public",
    "Poêle et foyer au bois",
    "Zonage",
    "Terrain insalubre - Domaine privé",
    "Voie cyclable - Planification - Service central",
    "Sécurité incendie - Inspection - Prévention",
    "Parcomètre",
    "Info - Collecte d'objets encombrants",
    "Logement - Insalubrité",
    "Bac roulant",
    "Élagage",
    "Changement d'adresse - Taxes eau et déchets",
    "Direction - Finances",
    "Personnel - Arrondissement",
    "Autre - Résidus verts",
    "*Analyse de l'eau potable",
    "Logement - Inspection",
    "Panneau de signalisation entretien prioritaire",
    "Z-Compteur d'eau résidentiel",
    "IRP - Villes non reliées au GDC",
    "*Lampadaire - Réparation",
    "Localisation / Entretien Entrée d'eau",
    "Élection et référendum",
    "Chalet de parc",
    "Greffe - Arrondissement",
    "Abattage d'arbre",
    "Document exigé par la ville",
    "Signalisation écrite -  Entretien",
    "Signalisation - Neige",
    "Graffitis - Domaine privé",
    "Nettoyage du domaine public",
    "Plomberie.",
    "Encombrants non ramassés",
    "Logement social et communautaire",
    "Nuisance animaux domestiques",
    "Taxes locatives",
    "*Rendez-vous - Permis",
    "Intervention de stationnement - Enquête",
    "*Bac de déchets - Livraison",
    "Utilisation illégale de l'eau",
    "Plantation d'arbre",
    "Borne d'incendie - Entretien",
    "Pavage - Réparation",
    "Espace pour la vie",
    "Habitation - Divers - Service central",
    "Balai mécanique",
    "Éclairage - Études",
    "Piscine ou spa privés",
    "Gel Entrée d'eau",
    "Signalisation - Circulation - Études",
    "Distribution de végétaux",
    "Vente-débarras",
    "*01 - Demande d'intervention 5700",
    "IRP - Périmètre de sécurité",
    "Info - Collecte de déchets",
    "Dérogation mineure",
    "Clôture privée",
    "Z-Test de pression d'eau",
    "*Internet - Arrondissement",
    "*Festival et animation publique",
    "Autre - Bureau d'arrondissement - Service à la clientèle",
    "Voie cyclable - Études",
    "Bureau du maire",
    "Agrile du frêne - Divers",
    "Trottoir ou bordure - Réparation",
    "Bureau de l'inspecteur général",
    "Compost",
    "Maladie ou insectes - Arbre",
    "Pont et tunnel",
    "Archives et règlements d'arrondissement",
    "Éviction",
    "*Jeux, équipements ou mobilier",
    "Internet - Portail central",
    "Autre - Collecte de déchets",
    "Caisse de retraite",
    "Communications - Arrondissement",
    "Carte d'Accès arrondissement",
    "Événement local",
    "Z-Trou d'homme",
    "Résidus domestiques dangereux",
    "Extermination à l'extérieur - Insectes",
    "Bureau de l'ombudsman",
    "Écoquartier",
    "Maires et élus d'arrondissement",
    "Recyclage - Autre",
    "Numéro municipal",
    "Sécurité incendie - Pompier - Camion - Caserne",
    "IRP - Utilité publique",
    "Changement d'adresse - Taxes foncières",
    "Clôture et haie privée",
    "Enseigne commerciale",
    "Recherche d'encaissement",
    "*Intervention constat d'infraction SRRR",
    "Services Techniques - Varia",
    "NE Plus Utilisé - Info - Collecte de MO",
    "Location d'immeuble",
    "*Bac de MO - Modification de volume.",
    "Collecte des matières organiques",
    "Grilles de zonage - Distribution",
    "Vandalisme ou accident - Arbre",
    "Permis - Neige - Domaine public",
    "Aide au relogement",
    "*Bac de recyclage Endommagé, perdu, volé",
    "Gazon ou mauvaises herbes - Domaine public",
    "Mobilier de parc",
    "Graffitis - Domaine public",
    "Conseil d'arrondissement",
    "Horticulture - Divers",
    "*Autre - Inspection circulation",
    "Autre - Construction",
    "Autre - Maires et élus d'arrondissement",
    "IRP - Demande onde radio",
    "Mobilier urbain",
    "*Planétarium",
    "Voie cyclable - Marquage et signalisation écrite",
    "Aménagement de parc",
    "Communications corporatives",
    "Puisard/TH-Première intervention",
    "Développement social",
    "*Bac de recyclage - Modification de volume",
    "Camp de jour",
    "Gazon - Réparation",
    "Extermination à l'extérieur - Rats",
    "Autre - Zonage",
    "*Bac brun",
    "Encaissement et remboursement",
    "*Inscription - Sports",
    "Permis de démolition",
    "*Bac de recyclage - Endommagé, perdu, volé",
    "Logement - Réparation",
    "Rénovation de bâtiment à valeur patrimoniale",
    "MO - Non ramassées",
    "Recyclage - Non ramassé",
    "Déblaiement/Chargement",
    "Distribution de sacs",
    "Z-Borne-fontaine - Installation, retrait ou déplacement",
    "Marquage de la chaussée - Nouveau",
    "Info - Collecte de MO",
    "Demande de permis d'occupation temporaire",
    "Appel d'offre et soumission d'arrondissement",
    "*Info générale agrile du frêne.",
    "*Mobilier urbain (entretien)",
    "Chien agressif",
    "Chien sans permis",
    "Conseil d'agglomération",
    "Composition des divers conseils et commissions",
    "Marquage de la chaussée - Existant",
    "Horticulture - Entretien",
    "Gazon ou herbes hautes - Domaine privé",
    "Dépôt sauvage - Domaine public",
    "*Autre - Eau - Divers",
    "Pavé uni - Réparation",
    "Ramonage",
    "Déchets - Non ramassés",
    "Affichage - Illégal",
    "*Bac de déchets - Modification au volume",
    "Complexe sportif Claude-Robillard",
    "Archives et règlements - Service central",
    "*Complexe sportif",
    "Support à vélo",
    "Direction - Affaires pénales et criminelles",
    "Aréna Maurice-Richard",
    "Feux de circulation - Nouvelle installation",
    "Essouchement",
    "*Autre - Culture - Activité",
    "Recettes diverses",
    "*Activité culturelle pour tous",
    "Anciennes carrières",
    "Voirie - Études techniques - Trottoir ou bordures",
    "*Cueillette de déchet en vrac",
    "Dommage - Racines d'arbres",
    "Subvention locale - Arrondissement",
    "Demande de rapport",
    "Dépôt sauvage - Terrain privé",
    "*Pesticides - nids de guêpes",
    "Prise de rendez-vous",
    "Couleur, odeur ou goût anormal de l'eau",
    "Encaissement - Oasis",
    "Autre - Salubrité",
    "Billet de dépôt à neige",
    "*Autorisation de coupe d'arbre privé",
    "Certificat de vie et résidence",
    "*Gazon endommagé",
    "IRP - Poste d'essence",
    "*Vente d'un compteur d'eau",
    "Signalisation cachée par des végétaux",
    "*Signalisation écrite - Nouveau",
    "*Biodôme",
    "*Maison de l'environnement",
    "*Compteur d'eau ICI (Industries - Commerces - Institutions)",
    "Géomatique",
    "*Permis - Bruit - Commerce",
    "*Logement Montréal-Nord",
    "Encombrants sortis en temps prohibé",
    "Sports et loisirs - Natation inscription",
    "*Activités sportives",
    "Changement d'adresse - Taxes locatives",
    "Avis-Alertes aux citoyens",
    "*Inspection - Déchets - Dépôt illégal",
    "Mobilité électrique libre-service",
    "*Logement insalubre",
    "*Insectarium",
    "*Puisard - À nettoyer",
    "*SRRR - Nouveau secteur",
    "Bruit - Autre",
    "Greffe - CA - Registre des questions",
    "Entreposage non autorisé -Terrain privé",
    "*Eau rouillée (ou colorée)",
    "*Eau Colorée - Études",
    "Collecte des feuilles mortes",
    "*Puisard - À réparer",
    "*Tolérance de stationnement",
    "Bureau du cinéma et de la télévision",
    "Plainte contre un agent de stationnement",
    "Info matières acceptées - Collecte sélective",
    "Vente aux enchères",
    "*Activités aquatiques.",
    "Nid de guêpes",
    "*Puisard - Nettoyage - Ruelle",
    "Logement - Vermine ou rongeurs",
    "Balcon",
    "Adhésion",
    "*Abattage d'arbre privé",
    "Cannabis",
    "Autre - Greffe - Archives et règlements d'arrondissement",
    "Acquisition de ruelle",
    "*Animaux - cueillettes",
    "Complexe environnemental de Saint-Michel",
    "Utilité publique - Excavation",
    "*Voirie - Collecte appareil avec gaz réfrigérant",
    "*Sac protection de Matelas - Distribution",
    "*Bac de déchets - Endommagé, perdu, volé",
    "100 - Demande d'intervention et Assistance",
    "Correspondance adressée aux élus ou à la direction",
    "*Bac de recyclage - Livraison",
    "Retour DDS",
    "*Inondation dans le sous-sol",
    "Voirie - Études techniques - Pavage",
    "Borne-fontaine - Projets spéciaux",
    "Développement culturel - Central",
    "Piscine non clôturée",
    "*Installation de cage",
    "Concours horticole",
    "*Autre - Feux de circulation - Entretien",
    "Occupation non-autorisée",
    "*Plateaux sportifs",
    "Graffitis haineux",
    "*Autre - Égout - Refoulement",
    "Entrée charretière",
    "Borne-fontaine - Moins de 8 semaines",
    "*Abribus - Entretien",
    "*Inspection des aliments",
    "Chat sans permis",
    "Borne-fontaine - Plus de 8 semaines",
    "IRP - Espace clos",
    "*SRRR - Modification secteur existant",
    "Toponymie",
    "Crue des eaux - Nettoyage - Collectes",
    "IRP - Station de pompage",
    "Renouvellement",
    "*Cours aquatiques",
    "*Mesure d'apaisement",
    "Encaissement - Urbanisme et Permis",
    "Direction générale",
    "*Apaisement de la circulation",
    "*Autre - Horticulture - Entretien",
    "*Permis - Patrimoine",
    "Voirie - Divers - Transport",
    "**Autre - Centre des loisirs",
    "*Vitesse excessive",
    "Autre - Occupation temporaire du domaine public",
    "Direction - Immeubles",
    "Enseigne temporaire - Domaine privé",
    "*Vente de garage",
    "*Vignette mensuelle et journalière",
    "Statues, sculptures et plaques - Entretien",
    "*Puisard - Réparation - Ruelle",
    "Info jour de collecte - Collecte sélective",
    "Encaissement - Stop +",
    "Distribution de compost",
    "Balcon malpropre",
    "*Bac de MO - Livraison.",
    "Soutien Site web Info-Remorquage",
    "Autre - Collecte des encombrants",
    "Rampe de mise à l'eau",
    "Entrée d'eau en plomb-Demande de filtre",
    "Autre - Permis - Divers",
    "Info - Collecte de résidus verts",
    "Animaux perdus/trouvés",
    "Surveillance des travaux - Problèmes à la suite de travaux",
    "Éclairage planification - Service central",
    "*Abattage de frêne privé",
    "*Jardins - Renouvellement",
    "Direction - SMVTP",
    "*Marches - Courses - Calèches - Tournages",
    "Location de salles",
    "*Puisard bloqué",
    "Haie privée",
    "Extermination à l'intérieur - immeuble ville",
    "Logement - Chauffage",
    "Boîte de service",
    "*Sports et loisirs - Inst-Piscine",
    "*Eau brune",
    "Remise vignettes journalières",
    "Direction - Diversité sociale et sports",
    "NE Plus Utilisé - Bac de MO - Modification de volume",
    "Bâtiment vacant ou à barricader",
    "CCU",
    "*Puisard - Réparation - Rue",
    "Bureau du vérificateur général",
    "Autre - Urbanisme",
    "MO - Avis de courtoisie",
    "*Inscription - Activité récréative",
    "Autre - Collecte de MO",
    "*Nuisance - excrément",
    "Pression basse",
    "Pesticides - arbres",
    "Surveillance des travaux - Chantier rues et trottoirs",
    "Résidus verts - Non ramassé.",
    "*Autre - Eau - Fuite d'eau",
    "Éclairage nuisible.",
    "Autre - Taxes",
    "Auto abandonnée, roulotte, remorque, palette",
    "*SRRR - Autre",
    "*Bac de MO - Endommagé, perdu, volé.",
    "*Jardins communautaires - Divers",
    "820 - Animaux",
    "Occupation périodique du domaine public",
    "Éclairage existant - Entretien (Lampadaire privé)",
    "Vignette - Stationnements municipaux",
    "Bruit - Commerce et industrie",
    "Réfrigérateur ou congélateur",
    "*Stationnement ou débarcadère pour handicapés",
    "Retrait de chèque",
    "Plainte",
    "*UIR - Météo",
    "*Stationnement courte durée",
    "Programmation des feux",
    "Transport hors normes",
    "Assermentation - Information générale",
    "Logement en sous-sol",
    "*Piétonnisation",
    "Compteur coule",
    "Permis - Conversion en copropriété divise",
    "Panier de parc à vider",
    "*Salubrité",
    "*Comité de circulation",
    "*Vitesse",
    "Mesures d'urgence - Gestion en arrondissement",
    "*Réservation - Terrain de tennis",
    "*Aide - Problèmes financiers - Nourriture",
    "Signalisation - Études - Personnes handicapées",
    "*Camp de jour - Inscription",
    "*Autre - Sports et loisirs - Activités",
    "*Plomb - Remplacement de service d'eau",
    "Z-Inspection d'égout privé",
    "*Inspections en Arrondissement",
    "Une naissance / un arbre",
    "Autre - Communications",
    "*Nouvelle demande de bac brun",
    "Encombrants - Avis de courtoisie",
    "*Circulation - Vitesse",
    "*Info - Procédure événement spécial",
    "*Demande d'information - Taxes",
    "*Autre - Centre des loisirs",
    "*Jardins communautaires",
    "Plainte fonctionnement",
    "*Regard à réparer",
    "Inspection de logement",
    "Signalisation endommagée Vm",
    "Réception d'un plaidoyer",
    "Direction - DSI",
    "*Nouveau mobilier urbain",
    "*Danger potentiel - Arbre privé",
    "Permis personnels - Guides touristiques - Entrepreneurs sans place d'affaires",
    "Arbre - Abattage d'arbre privé",
    "*555 - Patrouille ciblée",
    "Création d'un SIMU",
    "Greffe - Profils et statistiques",
    "Entretien général",
    "*Autre - Éclairage existant",
    "Renseignements nouveau résident",
    "*Feux piétons",
    "Environnement - Recyclage - Bac 240 lt - Livraison",
    "Encaissement - Gescour",
    "Information sur les ventes-débarras",
    "*Signalisation - Études",
    "*Information sur constat d'infraction",
    "*Informations sur assemblée",
    "Immeuble - Réparation",
    "*Autre - Aréna",
    "Eau - Soutien aux opérations - Réseau secondaire",
    "*Vignette temporaire - Stationnement sur rue",
    "*Événements privés",
    "Environnement - Recyclage - Bac 240 lt - Endommagé, perdu, volé",
    "Pelouse - vers blancs PR",
    "Bac - Endommagé, perdu, volé",
    "Crue des eaux - Réintégration",
    "*Danger potentiel - Arbre public",
    "Travaux (info) - Panneaux divers",
    "*Dos d'âne - Rue",
    "*Arrêt obligatoire (Stop)",
    "Demande d'un nouveau compteur",
    "Stationnement - Études",
    "Airbnb",
    "Maisons fleuries",
    "Autre - Compteur d'eau - Résidentiel",
    "Autre - Stationnement municipal",
    "Nettoyage d'égouts",
    "Solarium",
    "Code de langue",
    "Panier de rue à vider",
    "Dos d'âne",
    "*Fleurs annuelles",
    "*Autre - Étude de circulation en arrondissement",
    "IRP - Ascenseur",
    "Affiche autoportante - Domaine public",
    "Inspection des aliments",
    "1100 - Autres",
    "*Voirie - Mobilier urbain - Entretien et déplacement",
    "Inscription",
    "*Piscines publiques",
    "*COVID-19",
    "*Événements publics",
    "Acquisition de terrain",
    "Excréments terrain privé",
    "Bac roulant - Matières recyclables",
    "Autre - Affichage",
    "Recyclage - Avis de courtoisie",
    "*Travail mal effectué (Rés. alim)",
    "Bruit sur chantier de construction",
    "*Dépôt illégal - application de reglementation",
    "*Cas de quartier",
    "*E. T. - Mesures de modération de la circulation",
    "Test d'écoulement d'eau",
    "Dos d'ânes - ruelle",
    "*Vente - Billetterie",
    "*Édifice - Mobilier",
    "Égout - Crue des eaux - Villes liées",
    "*Stationnement",
    "*Bibliothèque - Choix et acquisitions",
    "Abattage d'arbre privé",
    "*E. T. - Stationnement ou débarcadère pour personnes à mobilité réduite",
    "*Élagage arbre privé",
    "*nuisances olfactives",
    "*Bac roulant vert (1 à 3 logements)",
    "*Chantiers PRR",
    "*Circulation-Intersection dangereuse",
    "collecte des résidus alimentaires - Demande de bac",
    "Budget",
    "*Épaves de Vélos",
    "*Sports et loisirs - aquatique",
    "*Feux de circulation",
    "Budget d'arrondissement",
    "Bornes de recharge publiques",
    "*Débarcadère école, garderie, institution",
    "*Nouveau mobilier de parc",
    "Permis - Logement - Nuisances animales",
    "Chevaux",
    "Eau - Qualité de l'eau",
    "Abattage d'arbre public",
    "Fermeture d'entrée et sortie de ruelle",
    "Liste d'attente - Stationnements municipaux",
    "Mesure d'apaisement - Circulation",
    "Bac -  Info collecte sélective",
    "*Inspection d'arbre public",
    "*Souche, tronc et branche de + 20 cm de diamètre à ramasser",
    "*Centre des loisirs - Location de salle",
    "Mesures d'apaisement",
    "*Corridors sanitaires",
    "*Activité culturelle - Jeunesse",
    "*Bibliothèque - Aide aux lecteurs",
    "*Haie publique",
    "AEC (Parc canin)",
    "*E. T. - Temps de la traverse",
    "Autre - Démolition",
    "Travaux publics - Plainte de tout genre",
    "*Bac Brun - Demande",
    "Travaux sans permis",
    "*Commandite et campagne de financement",
    "Info - Procédure événement spécial - BDC",
    "Demande d'une nouvelle signalisation",
    "*Arbre - Abattage permis d'abattage terrain privé",
    "Autre - Horticulture - Distribution de végétaux",
    "*Branchement d'égoût domaine public - Études",
    "Immeuble - Malpropreté générale",
    "Réception de chèque post-daté",
    "*Feuilles - nettoyage des parcs",
    "Bruit - Thermopompe et climatiseur",
    "Signalisation manquante VM",
    "*Neige - Permis de dépôt de neige",
    "Bicyclette abandonnée",
    "Bac roulant - Déchets",
    "Autre - Carte d'Accès arrondissement",
    "Thermopompe et climatiseur",
    "Infiltration dans bâtiment eau",
    "Eau Colorée - Autre",
    "Bac roulant - Résidus alimentaires",
    "Occupation bâtiment",
    "Puisard/TH-Refoulement/Débordement/Blocage",
    "*Camp de jour - Information générale",
    "Règlements - Distribution",
    "Documents archivés - Distribution",
    "Voirie - Banc",
    "CAFÉ-TERRASSE (PERMIS)",
    "*Aide - Problèmes financiers - Loyer",
    "*Réservation - Terrain de volley-ball",
    "*Autre - Culture - Installation",
    "*Poubelle lancée  (déchets)",
    "*Puisard - Grille brisée",
    "Ingénierie - Pavage",
    "Relevé CPTE",
    "Feuilles mortes dans la rue.",
    "Immeuble - Ventilation",
    "Déchets - Bac endommagé, perdu, volé",
    "Autre - Permis - Vente débarras",
    "Autre - Clôture et haie",
    "Coupe d'arbre privé sans permis",
    "Stationnement pour personnes handicapées",
    "Tolérance de stationnement",
    "*Fermeture de ruelle",
    "*Eau - Divers - Boîte de service à inspecter",
    "Voirie - Vibrations",
    "*Eau - Borne fontaine - Entretien",
    "Voirie - Poubelle",
    "Support DCI - Services numériques",
    "Environnement - Recyclage - Bac 240 lt - Non ramassé",
    "*Aquatique",
    "Piste cyclable déneigement",
    "*Permis - Borne-incendie",
    "Événements privés - SU",
    "Distribution de sac pour matelas",
    "*SODER - Fermeture",
    "*Boîte de service à vérifier",
    "*E. T. - Trottoir ou bordure - Réparation",
    "bac brun divers",
    "*Arbre - Maladie - Pucerons",
    "Déchets - Objet vol. à ramasser - Réfrigérateur, climatiseurs - Voirie",
    "*Nuisance chantier - Poussière",
    "*Bac de déchets Livraison",
    "*PRR-Travaux",
    "*Eau - Projet spécial",
    "Déchets - Demande de bac",
    "Asphalte travaux",
    "*Ne plus utiliser Bac roulant noir (déchets)",
    "*Bac roulant - Non ramassé",
    "*Feux de circulation - Accident",
    "Sacs d'emplettes",
    "Canopé",
    "Ingénierie - Trottoir, bordure",
    "*Bac de MO Modification de volume",
    "*Dos d'âne - Ruelle",
    "*Dos d'âne dans les ruelles",
    "Couvercle de puisard bruyant",
    "*PRR-Circulation",
    "Électricité - Édifices - Municipaux",
    "*Entretien des branchements d'égouts ou drains",
    "Vision vélo",
    "*Réservation - Terrain de badminton",
    "*Voirie - Pavage - Réparation - Rue",
    "520 - Stationnement",
    "*Activité communautaire",
    "REM - Occupation temporaire",
    "Panier de rue - Installation",
    "Bruit - des Carrières - Ombudsman",
    "Micropuçage",
    "*SRRR - Ajout ou retrait d'espaces",
    "*Bac de déchets Endommagé, perdu, volé",
    "*Stationnement - Débarcadère",
    "Événements publics - Loisirs",
    "*Centre des loisirs - Carte loisirs",
    "*Bac de recyclage Livraison",
    "*Activités sur glace",
    "*Shoebox - élus",
    "Immeubles municipaux - Éclairage",
    "Nettoyage de puisards - rues",
    "Pression Faible/Forte",
    "*Affaissement - Défonçage",
    "NE Plus Utilisé - MO - Non ramassées",
    "*Capital humain - Ressources humaines",
    "NE Plus Utilisé - MO - Avis de courtoisie",
    "*13 - Demande de circuler",
    "NE Plus Utilisé - Bac de MO - Endommagé, perdu, volé",
    "*Déversement des eaux usées",
    "NE Plus Utilisé -Autre - Collecte de MO",
    "Centres de traitement des matières organiques",
    "*Voie cyclable - Marquage et signalisation écrite",
    "Permis conteneur à déchets",
    "Activité - Billets de spectacle",
    "Un enfant, un arbre",
    "Antenne satellite",
    "*310 - Déchets",
    "*Modification secteur existant",
    "*11 - Bruit",
    "Débris sur chantier et rues",
    "*Patinoire extérieure - entretien",
    "Permis - Logement - Moisissures",
    "Asphalte - Coupes d'aqueduc et autres",
    "*03 - Affichage illégal",
    "*Réservation - Patinoire extérieure",
    "Planification des travaux - Études parcs",
    "Inspection vignette",
    "*30 - Corridors scolaires",
    "200 - Sécurité des bâtiments",
    "*Patinoire extérieure",
    "Planification des travaux - Études rues et trottoirs",
    "*Bac montréalais",
    "Encaissement - Occupation du domaine public",
    "Stationnement",
    "Culture - Installations - Bibliothèques",
    "Permis - Logement - Chauffage",
    "*Animaux perdus",
    "Déchets sortis en temps prohibé",
    "Déchets - Avis de courtoisie",
    "Permis - Logement - Défectuosité extérieure",
    "*Bibliothèque du Boisé",
    "*Chauffage",
    "*Parc - Patinoires extérieures",
    "Direction Culture Sports Loisirs Dév. Soc.",
    "*33 - Neige - Avis de courtoisie",
    "*UIR - SIT-Neige",
    "Planification des travaux - Études immeubles municipaux",
    "Avis de courtoisie - Neige",
    "*Bibliothèque - Prêt",
    "Sport et loisirs - Installation - Piscine",
    "*Location de terrains",
    "*Autres patinoires extérieures Ville-Marie",
    "*Boîte de service à mettre en ordre",
    "Couvercle de puisard absent ou déplacé",
    "*DI - réparation trou d'homme",
    "Assistance aux citoyens - Sinistre",
    "*Bac endommagé  (recyclage)",
    "*E. T. - Stationnement ou débarcadère pour commerce",
    "*Abribus - Installation",
    "*Puisard - Nettoyage - Rue",
    "*Culture et install - Bibliothèque",
    "*Parc chalet - Métiers",
    "*Abribus - Réparation",
    "*Environnement - Bac roulant - Demande  bac roulant",
    "*Circulation en transit",
    "*Bibliothèque - Utilisation et réservation d'équipement",
    "*Nuisance - jappement",
    "*Circulation - Intersection dangereuse",
    "Information transmise à un assureur",
    "*DI - fermeture d'entrée d'eau",
    "*Bac roulant - Livraison",
    "*Aide - Démarches administratives",
    "Technique - Trottoir ou bordure - Réparation",
    "Sport et loisirs - Installation - Aréna",
    "NE Plus Utilisé - Bac de MO - Livraison",
    "*Patinoire extérieure - vandalisme",
    "*Baisse de pression",
    "*Sports et loisirs -Act-Marché aux puces",
    "Sac de recyclage réutilisable",
    "*Projet Turcot - Bruit/Camionnage/Propreté",
    "Recyclage sorti en temps prohibé",
    "*Neige - Divers - Gazon",
    "Droits acquis",
    "Vente de mangeoire à oiseaux",
    "*Bibliothèque IB",
    "*Subvention CSLDS",
    "*Autre - Eau - Test de pression d'eau",
    "*Matériel à changer  (recyclage)",
    "*Grille de puisard déplacée",
    "Baril de récupération de l'eau de pluie",
    "Puisard/TH-Couvercle Abs./Déplacé",
    "*Immeuble - 815 Bel-Air",
    "*Surveillance et sécurité publique - Surveillance des travaux - Construction",
    "Résidus alimentaires - Bac brun (remis au comptoir)",
    "Égout - Crue des eaux - Évacuation",
    "*Voirie - Panier",
    "permis artisans sans place d'affaire calèche",
    "Sac pour matelas",
    "*Réparation - Gazon par l'entrepreneur",
    "*Environnement - Bac roulant - Brisé",
    "*Sports et loisirs - Inst-Aréna",
    "*CSST",
    "*Éclairage - Accident",
    "700 - Propreté",
    "*Addenda",
    "*Dépôt de garantie bancaire",
    "Sport et loisirs - Installation - Centre communautaire",
    "collecte des résidus alimentaires - Bac endommagés",
    "Usage du sol",
    "*Matériel à remplacer  (déchets)",
    "*Services administratifs-Sud-Ouest",
    "Technique - Pavé uni - Réparation",
    "Permis - Pesticide",
    "Herbes dangereuses",
    "*Info générale agrile du frêne",
    "Jardins communautaires",
    "*Neige - puisard glacé",
    "Permis - Logement - Non conforme",
    "*Réservation - Terrain de soccer",
    "*Parc - Aire d'exercice canin",
    "*Transmission d'une télécopie",
    "Programme de chats errants",
    "*Aide - Assistance aux personnes âgées",
    "Sport et loisirs - Installation - Jardin communautaire",
    "*Parc - Déneigement (sentier, chalet, immeubles)",
    "Menuiserie parc",
    "Direction Travaux Publics",
    "Eau - Manque d'eau",
    "Artistes - Artisans",
    "Retour de chèque permis animalier",
    "*Éclairage insuffisant",
    "Autre - Compostage - Distribution",
    "*Demande d'informations",
    "*Creusage pneumatique",
    "*Parc - Entretien de sentiers",
    "*Bibliothèque - Événements spéciaux",
    "Eau - Baisse de pression",
    "Sport et loisirs - Installation - Tennis",
    "PIIA",
    "*Anciennes carrières - Service central",
    "Couvercle de puisard - brisé",
    "Affiche fixée sur arbres ou arbustes",
    "*Événements spéciaux - Loisirs",
    "Permis - Logement - Aires libres",
    "Amuseurs publics",
    "*Sites de dépôt volontaire - Résidus alimentaires",
    "*Bac roulant - Endommagé, perdu, volé",
    "Vérification de lecture",
    "Corde à linge",
    "Permis - Logement - Vermines -rongeurs",
    "Résidus verts - Avis de courtoisie",
    "*Problème à la suite de travaux",
    "*Culture et install -Centre Leonardo da Vinci",
    "Travaux-Plantation d'arbre",
    "Café-terrasse",
    "*Réparation mineure (arr.)",
    "*Réparation branchement égout privée",
    "*Parc mobilier - Enlèvement - VM",
    "*Travaux reportés au printemps",
    "*Jeu d'enfant",
    "Vente de bacs à compostage",
    "*Bibliothèque - Animation",
    "*Réseau local",
    "Logement - Ventilation",
    "*Bac disparu  (recyclage)",
    "Voirie - Études techniques - Trottoir associe",
    "Voirie - Artériel",
    "Eau colorée - jaune, orange, brune, rouge/Particules",
    "*LaSalle - Avis d'ébullition",
    "Opération cadastrale",
    "Permis - Logement - Accumulation balcon",
    "collecte des résidus alimentaires - Bac non ramassés",
    "*Autre - Parc - Entretien",
    "*Nettoyage puisard (arr.)",
    "Affichage politique",
    "*Réservation - Terrain de baseball",
    "Grand parc - Agrile du frêne",
    "*Regard d'égoût déplacé",
    "Autre - Pesticide",
    "Entretien des patinoires",
    "Autre - Marquage de la chaussée",
    "*Parc - Jeux d'eau",
    "*Parc Angrignon - Demande d'information",
    "*Terrain de jeux",
    "Changement d'adresse",
    "Autorisation d'affichage sur propriété privée",
    "*Haie endommagée",
    "*Permis - Bruit - Résidence",
    "*Animaux trouvés",
    "*Arbre privé dangereux",
    "*Réparation (Fût et lentille)",
    "*Déchets hors des heures",
    "*Direction d'arrondissement - Bureau d'arrondissement",
    "*Bains libres",
    "*Parc - Terrain vacant (fauchage)",
    "*Mobilier urbain - Installation",
    "Marquage - Contrat pour la circulation",
    "*Voirie - Béton - Rue",
    "*Voirie - Pavage - Réparation - Ruelle",
    "*Arbre - Maladie et insectes - Domaine public",
    "*Fontaine - jeux d'eau",
    "Construction réseau local",
    "Autre - Subvention locale - Arrondissement",
    "Encaissement - Taxes",
    "*Nouveau secteur",
    "*Gazon Endommagé-Travaux par la Ville",
    "Distribution des publications arrondissement",
    "*Branchement d'égout - Domaine privé",
    "*À la demande de la DAUSE - Inspection d'arbre privé",
    "*Branchement d'égout - Domaine public",
    "*Permis - Bruit - Travaux",
    "*Programme - Un enfant, un arbre",
    "*Abattage d'arbre - terrain prive",
    "*Génie - Émission de permis",
    "Permis promeneur de chiens",
    "*Réservation - Terrain de basketball",
    "*Jardin communautaire Sud-Ouest résidus verts",
    "*Spectacle",
    "*Puisard - Réparation",
    "*Parc - Fontaine, jeux d'eau, irrigation - Entretien",
    "*Autre - Festival et animation publique",
    "*Parc - Mobilier - Jeux - Vandalisme",
    "*Projet Turcot - Divers",
    "*Piscine malpropre",
    "Permis - Logement - Défectuosité intérieure",
    "*Occupation - Terrasse",
    "*Réservation - Terrain de bocce",
    "*Gazon Endommagé-Opération déneigement",
    "*Réservation - Aire de pique-nique",
    "Ralenti inutile - Terrain privé autre que chantier.",
    "*Nourrit les oiseaux",
    "*Permis disjonction (arr.)",
    "Démolition de bâtiment résidentiel",
    "Plans de zonage - Distribution",
    "Éco-campus Hubert Reeves",
    "*Surveillance et sécurité publique - Surveillance du territoire",
    "*Édifice - Menuiserie",
    "Débarcadère - Personne à mobilité réduite",
    "Piscine - Propreté.",
    "*Extermination à l'extérieur - Guêpes",
    "Excès de vitesse - Surveillance SPVM",
    "Panneaux électroniques",
    "Travaux Élagage",
    "Végétaux privés",
    "*Groupe de travail - vitesse",
    "*Demande d'information par médias",
    "400 - Incivilités et infractions",
    "Déchets - Illégal - Recyclage - VM",
    "*Réservation - Terrain de football",
    "*Transformateur de lumière bruyant",
    "*Arbre - Demande de propriété",
    "* Fuite d'eau (arr.)",
    "*Bac brun endommagé",
    "Climatiseur",
    "*Loisirs en ligne",
    "*Aide - Problèmes financiers - Vêtements",
    "**Centre des loisirs - Carte loisirs",
    "*Autre dommage",
    "*Don, octroi et bourse",
    "Vision vélo (Acceptabilité)",
    "*Événements spéciaux",
    "Direction Développement du territoire",
    "Environnement - Recyclage - Bac 360 lt - Livraison",
    "*Occupation du domaine public (Permis)",
    "*Sports et loisirs - Programme LCM",
    "*Contrôle animalier - Berger blanc",
    "Autre - Dérogation",
    "*Édifice - Peinture",
    "*Panier de rue à vider",
    "*Voirie - Trottoir - Réalisation",
    "*Horaire non-respecté  (recyclage)",
    "*Entretien général",
    "*Bac roulant endommagé",
    "*Signalisation manquante ou cachée par des végétaux privés",
    "*Plomb Programme de remplacement",
    "*Déchets mal disposés",
    "*Programmation culture, sports et loisirs",
    "*Parc - Aménagement sentier",
    "*Aréna - Réservation",
    "*Bruit (eau) dans la maison",
    "Surveillance des travaux - Chantier parcs",
    "Permis - Logement - Insalubrité (logement ou bâtiment)",
    "Occupation permanente du domaine public",
    "*Parc aménagement - Travaux en cours",
    "*Chien dangereux",
    "*Aide - Recours juridiques, informations, références",
    "*Vente de documents",
    "*Occupation permanente des utilités publiques",
    "*Réservation - Piste d'athlétisme",
    "*Jardins communautaire",
    "Pelouse - autres",
    "*Feuilles mortes - Domaine public",
    "*Éclairage",
    "**Centre des loisirs - Location de salle",
    "*Signalisation - Nouvelle installation",
    "Événement public",
    "Présence d'animal sauvage",
    "CVP - Raccordement aqueduc/égout",
    "Permis CSRM",
    "Débarcadère - École",
    "*Stationnement - Études",
    "*Sens de rue",
    "*Déneigeur privé",
    "CVP - Entrée charretière",
    "Drapeau",
    "Autre - Environnement - Collecte de feuilles ou arbres de Noël",
    "*Localisation de fuite",
    "Changement d'adresse effectué - Taxes foncières",
    "*Horaire de collecte non-respecté  (déchets)",
    "*DI - signalisation installation",
    "*Bac de MO Livraison",
    "*Plateaux sportifs - entretien",
    "*Test de pression (arr.)",
    "*ÉLU - TP Bureau technique",
    "*Inspection des égouts",
    "*320 - Déneigement",
    "*ÉLU - Direction TP",
    "Marches - Courses - Calèches - Tournages - SU",
    "Surveillance particulière - SPVM / AMD",
    "*Nuisance -neige",
    "Eau - Travaux après coupe d'eau",
    "600 - Signalisation",
    "Renseignements - Pesticide",
    "*Transports",
    "*Panier de rue-Ajout/Retrait",
    "*Stationnement ou débarcadère pour personne à mobilité réduite",
    "Environnement - Recyclage - Bac 360 lt - Endommagé, perdu, volé",
    "*Ent. édif. mun. - Mairie, Serv. tech., Station de pompage",
    "*Égout - Puisard - Réparation à effectuer",
    "*Travail mal fait  (recyclage)",
    "Voirie - Mobilier urbain - Clôture en fer forgé",
    "*E. T. - Nouvelle construction de rue",
    "*Déchets",
    "*Parc - Aménagement aires de jeux",
    "*Réparation majeure (arr,)",
    "Affiche autoportante - Domaine privé",
    "*Refoulement (arr.)",
    "Réparation - regards d'égout",
    "Voirie - Nettoyage du domaine public - Panier de rue",
    "Environnement - vente de garage",
    "*Mobilier urbain (nouveau)",
    "Eau - Boite de service",
    "Plainte patrouilleur canin et fournisseur service animalier",
    "*Limites de vitesse",
    "*Camionnage",
    "*Nuisances (diverses)",
    "*Parc - Gazon - Tonte",
    "Plastiques à usage unique",
    "Utilisation d'une BF non-autorisée",
    "Travaux Abattage",
    "Arbre - Suivi de plantation",
    "*Eau - Borne fontaine - Réparation",
    "*Puisard - Nettoyage - Contrat",
    "*Réservation - Terrain de pétanque",
    "*Bac roulant volé",
    "*Parc - Aménagement enseigne et mobilier",
    "Dépôt illégal-Ramassage",
    "*Nids de guêpes",
    "*Direction d'arrondissement - DA",
    "Révision du stationnement",
    "*Permis - Clôture et haie - Demande Information",
    "*Parc - Chalet entretien ménager",
    "Nouvelle construction - Installation pour déchets",
    "Déneigement - Rayon",
    "*Arbre - Plantation - Domaine public",
    "*Eau Divers - Chambre de vanne - Réparation",
    "*Odeur (nuisances)",
    "Bac roulant - Matières organiques",
    "Permis",
    "Environnement - Recyclage - Bac 360 lt - Non ramassé",
    "*Bac non remis à l'endroit prévu  (recyclage)",
    "*Plainte fermeture d'installations aquatiques",
    "*Bixi",
    "*DI - signalisation mise aux normes",
    "*Arbre - Branches à ramasser",
    "*Extermination à l'extérieur - Nid de guêpes",
    "*Fontaine à boire,jeu d'eau,fontaine décorative",
    "*Vente de garage (infraction)",
    "Bac de recyclage -Endommagé, perdu, volé",
    "*Signalisation écrite - Entretien",
    "Surveillance des travaux - Chantier immeubles municipaux",
    "Déneigement - Débarcadère",
    "Agir - Tarification",
    "Animal perdu ou trouvé",
    "*Nettoyage parc",
    "Chien qui aboie",
    "*Fuite sur conduite de borne-fontaine A/C",
    "*Déneigeurs privés - Poteaux",
    "Inscription - École-Écolo.",
    "Réparation de puisards - rue",
    "*999 - Sécurité demandée sans précision",
    "*Signalisation écrite - nouveau",
    "Article de jeux sur domaine public",
    "*Parc - Aménagement terrains sportifs ou récréatifs",
    "*Voirie - Mobilier urbain - Études",
    "*Signalisation écrite - Entretien (annulée)",
    "*E. T. - Feux de circulation",
    "*Sports et loisirs - Arénas",
    "Borne électrique",
    "Services administratifs",
    "*Aide aux sinistrés - Incendie, inondation, vague de chaleur",
    "Bac de recyclage",
    "*Déneigeurs privés - Enseigne",
    "*Sapin décoratif - parc",
    "Pression trop forte",
    "*Entretien des patinoires",
    "Bac - Distribution",
    "*Travail mal fait (débris)  (déchets)",
    "*Déneigeurs privés - Permis",
    "Débarcadère - Garderie",
    "*Signalisation manquante ou endommagée",
    "Puisard/TH-Clé ou objet",
    "*Borne",
    "*Stationnement-Études",
    "*Zone de livraison",
    "Greffe-Bureau des élus",
    "Borne d'incendie - Installation, déplacement, utilisation",
    "*Neige - Opération neige",
    "*Regard d'égout réparation",
    "*Résultat d'ouverture",
    "Permis de coupe",
    "*Erreur",
    "Sports et loisirs - Installations - Piscines et plage",
    "Branchement égout Brisé/Déformé",
    "*Égout - Puisard - Nettoyage",
    "*Bac brun lancé",
    "*Neige VM",
    "*Entraves",
    "*Sports et loisirs - Terrains extérieurs",
    "Puisard/TH-Couvercle bruyant",
    "*Bibliothèque BENNY",
    "Plaque déplacée",
    "*Permis - Terrain - Entreposage non autorisé - Visible de la voie public",
    "Abribus - Nettoyage",
    "Agir - 5 minutes ou moins",
    "*Nid-de-poule - Concours",
    "*Voirie - Égoût - Bloqué",
    "*Relevé de pression",
    "*Parc mobilier - Entretien - VM",
    "*Voirie - Pavage - Entretien",
    "*Bac de recyclage  Modification de volume",
    "*Bac lanc��  (recyclage)",
    "CAFÉ-TERRASSE (DOMAINE PUBLIC)",
    "*E. T. - Limites de vitesse",
    "*Information aux citoyens (recyclage)",
    "*Carte d'abonnement à la bibliothèque",
    "*Terrains extérieurs",
    "*Bâtiment - Plomberie",
    "*Parc - Transport - Livraison",
    "*Aide - Santé mentale",
    "Immeubles municipaux - Plomberie",
    "*Feux sonores pour handicapés visuels",
    "CVP - Débranchement aqueduc/égout",
    "*Extermination à l'intérieur - Insectes",
    "CSPSA (SPCA)",
    "*Parc - Mobilier et signalisation - Bris et entretien",
    "*Bac de MO Endommagé, perdu, volé",
    "Agir - 15 à 20 minutes",
    "*Parc - Poubelles et déchets",
    "Réparation de puisard - ruelle",
    "*Parc - Mobilier et signalisation - Installation",
    "Bac de MO sorti en temps prohibé",
    "Bac de déchets - Endommagé, perdu, volé",
    "Dos d'âne - 2",
    "Entretien - Dos d'âne de ruelle",
    "*Permis - Cabanon",
    "*Non-respect de l'horaire (Rés. alim)",
    "Zone livraison",
    "Graffitis sur bâtiment public",
    "*Luminaire à installer",
    "*Inspecteurs Demandé",
    "*Éclairage  terr.sportif",
    "E.T. Support à vélo",
    "Loisirs - Entretien Léger",
    "Agir - plus de 20 minutes",
    "Voirie - Divers - Rue - Travaux majeurs",
    "*Bacs à fleurs, corbeilles, lits de plantation",
    "*Entrée charretière - Réfection",
    "*Puisard -Réparation - Entretien",
    "Marquage de la chaussée - Travaux majeurs",
    "*Bac de déchets Modification de volume",
    "bac brun non ramassé",
    "Bureau des élus",
    "*Module de jeux",
    "Agir - 5 à 10 minutes",
    "Direction Performance, Greffe et Services adm.",
    "*Centre des loisirs - Remboursement d'activité",
    "*Marquage",
    "*Arbre - Maladie - À revoir",
    "Bac résidus alimentaire",
    "Recyclage du verre",
    "*Parc - Éclairage - ouverture et fermeture",
    "*Branchement d'égout réparation",
    "*Faire relevé du ou des compteurs",
    "Favorable - Implantation",
    "Stationnement municipal - Travaux majeurs",
    "Banc",
    "Entrée charretière - circulation",
    "*Circulation - Fluidité",
    "510 - Routier / Circulation",
    "*Abattage/Essouchement exécution",
    "Mobilier urbain - Installation",
    "*Seringues",
    "*Contenant non conforme",
    "*Extermination rats",
    "*Réparation - section bâtiment",
    "Immeubles municipaux - Clôture",
    "*Centre communautaire",
    "Jardin de rue",
    "*Branchement d'égoût domaine public - Travaux",
    "*Camion",
    "800 - Bruits",
    "*Voirie - Protecteur d'arbre",
    "Jeux d'eau",
    "Parc mobilier - Ajout - VM",
    "*Information citoyen (déchets)",
    "*Réglementation - Distribution bac",
    "*Permis - Réfection de coupe",
    "Feux de circulation - Programmation",
    "*Shoebox - BAM",
    "Égout - Crue des eaux - Évacuation - Villes liées",
    "Encaissement - RH",
    "Signalisation - Ligne de rue",
    "Environnement - arrosage",
    "Eau - Ponceau - Demande d'ingénierie",
    "Voirie - estimation rebut",
    "Culture, sports, loisirs et développement social",
    "*Pesticide - Demande de permis",
    "Poubelle",
    "Support à vélos",
    "Environnement - eau stagnante",
    "Ingénierie - Égout, puisard",
    "*Clôtures et haies publiques",
    "Arbres ruelles",
    "*Sacs - chien - 2016",
    "Voirie - Trou d'homme - Réparation",
    "Pesticide - Service central",
    "*Puceron",
    "*Eau - Mettre boîte de service en ordre",
    "**Réservation - Terrain sportif extérieur",
    "Immeuble - Serrure porte d'entrée",
    "Distribution de balise",
    "**Complexe sportif",
    "*borne fontaine à déneiger",
    "Bruit - Travaux",
    "Compteur Résid. Entretien",
    "Encaissement - Ressources Financières",
    "*Opération 1er juillet",
    "*VAS",
    "Dos d'âne - ruelle - 2",
    "Compteur bruyant",
    "900 - Réglementation municipale",
    "Bac de déchets - Livraison",
    "Transit mall",
    "Herbe à poux",
    "Travaux -Maladie-Insectes",
    "Défonçage de la chaussée",
    "*E. T. - Pavage - Réparation",
    "*E. T. - Arrêt obligatoire (Stop)",
    "*E. T. - Sens de rue",
    "Vision vélo (Utilisation)",
    "*E. T. - Stationnement courte durée",
    "Bac-RÉPARATION",
    "*Poubelle non-remise à l'endroit prévu  (déchets)",
    "Puisard/TH-Couvercle Brisé",
    "*Élagage exécution",
    "Utilisation d'un souffleur à feuilles",
    "MTLWiFi - Support technique",
    "Avis d'infraction - Neige",
    "Signalisation non autorisée - Analyse",
    "*Gazon réparation",
    "SRRR - Émission de vignettes",
    "Construction ruelle",
    "*Signalisation manquante ou endommagée (incluant la signalisation de stationnement)",
    "Entrave sans permis",
    "*Support à vélo-Ajout/Retrait",
    "Abribus - Réparation",
    "Retrait ou récupération de vélo",
    "Milieux de vie verts et actifs",
    "Réparation de puisards - trottoir",
    "Immeubles municipaux - Entretien ménager",
    "Enseigne temporaire et banderole sur propriété publique.",
    "Affiche propreté",
    "Pompe qui fonctionne sans arrêt",
    "Encaissement - Centre des Loisirs",
    "Agir - 10 à 15 minutes",
    "*Demande de renseignement - signalisation temporaire",
    "Réparation de gazon - Contrat",
    "*Bibliothèque",
    "*Tennis",
    "Clôture publique",
    "Déchets - Illégal - Conteneurs - VM",
    "Demande d'information d'arbre privé",
    "Décarie",
    "*Permis - Construction - Nuisances",
    "Affaires - Demandes courriel",
    "Signalisation non autorisée - Ramassage",
    "*Entretien d'édifices municipaux - Plomberie",
    "Dos d'âne RUELLE",
    "Dépôt illégal déchet - ruelle",
    "MTLWiFi - Demande d'installation",
    "Compteur ICI Vérification de lecture",
    "Gout, odeur - Autre que Chlore et Oeufs pourris",
    "Bac de MO - Endommagé, perdu, volé",
    "Compteur ICI Pose/Enlèvement",
    "Rapport annuel/Technique Eaux usées",
    "Gout, odeur - Chlore et Oeufs pourris",
    "Bac de recyclage - Modification de volume",
    "Bac de recyclage -Livraison",
    "Demande Info.Technique",
    "*Permis - Clôture & haie - Aménag. paysager public non conforme",
    "*Ent. édif. mun. - Loisirs - Métier(Plomberie, Électricien, Mécanique)",
    "*Neige - Dommages déneigement en régie",
    "*E. T. - Eau - Divers - Réparation",
    "*Avis d'absence",
    "*Édifice - Chauffage - Climatisation",
    "*Poubelles",
    "*Système d'alarme",
    "Encaissement - Revenus liés aux évictions",
    "Obstacle en marge avant",
    "*DI - asphalte",
    "*Édifice - Serrurerie",
    "*DI - métiers",
    "*Entretien - Enseigne commerciale",
    "*Arbre - branches à ramasser",
    "*DI - mécanique du bâtiment",
    "Chien dans un parc",
    "*Réparation - bâti",
    "Éclairage - Extérieur - Parc",
    "*Déneigement - Édifices municipaux",
    "*Modification de panneau - Entretien",
    "*Extermination à l'extérieur - Fourmis",
    "Nettoyage de puisards - ruelles",
    "*E. T. - Support à vélo - Nouveau",
    "*E. T. - Banc de rue - Nouveau",
    "Graffitis sur signalisation",
    "*Transport de matériel et d'équipement",
    "*DI - graffitis",
    "Mécanique automobile",
    "*DI - Intervention eau/puisard à planifier",
    "Plomberie - Chalet",
    "*08 - Porter assistance au SSIM",
    "Parc - Mobilier - Transport",
    "*Conseil d'arrondissement - AUP",
    "*Conseil d'arrondissement  - Aucun suivi",
    "*DI - boites (services ou vanne)",
    "*Conseil d'arrondissement - TP",
    "*12 - Danger ou débris sur la voie publique",
    "*Ent. édif. mun. - Autres bâtiments",
    "Demande de stationnement - Personnes handicapées",
    "Immeubles municipaux - Maçonnerie",
    "Voirie - Camion citerne",
    "Piscine - Électricité",
    "*Chalet - Peinture",
    "Plomberie - Bâtiments",
    "*Bâtiment - Entretien",
    "*Bac roulant vert (collectes sélectives)",
    "*DI - Voirie divers transport",
    "*DI - projet immeubles et matériels roulants",
    "*Effondrement (arr.)",
    "*Horticulture - Fleurs entretien (plates bandes et bacs)",
    "Électricité - Parc - Chalet",
    "*Vérifications et suivis - RMT-PRR",
    "*Eau - Divers - Boîte de service - Excavation pneumatique",
    "*Bâtiment - Menuiserie",
    "*Parc - Propreté aire de jeux",
    "Plomberie - Fontaine",
    "Stationnement municipal - Propreté",
    "*Parc - Appareils de jeux - Entretien",
    "*Clôture et haie cour avant Saint-Léonard",
    "Chien errant",
    "*E. T. - Marquage",
    "*Voiture au rancart (nuisances)",
    "*Banc-Ajout/Retrait",
    "*Parc - Entretien - Clôture",
    "Autre - Déchets - Collecte mécanisée",
    "*Bac brun disparu",
    "*Permis - Clôture & haie - Aménag. paysager privé non conforme",
    "*DI - signalisation poteau",
    "*Limiteur de vitesse - Ruelle",
    "*Eau - Divers - Boîte de service à ajuster",
    "Égout - Entretien",
    "Ciment",
    "*Arbre - Élagage - À revoir",
    "*Chalet - Menuiserie",
    "Env. - Graffitis - Edif public - Infrastructure, Voirie",
    "*DI - réparation d'égout",
    "Barricades métalliques",
    "*DI - horticulture",
    "*Marquage au sol (par citoyen)",
    "Permis - Logement - Accumulation odeurs",
    "*DI - vanne",
    "*Info-travaux - Répar. majeure - construc.,trottoir,pavage",
    "Animal à ramasser",
    "*Éclairage - entretien",
    "Plomberie - Piscine",
    "Mauvaises herbes - terrain privé",
    "*Dossier interne : Terrain insalubre",
    "*Parc - Terrains - terrains de balle",
    "*Entretien hivernal",
    "*Égout - Puisard - Grille à remplacer",
    "*Déchets - Collecte - Plainte, Vérification",
    "Encaissement - Aréna",
    "*Système d'irrigation",
    "Animaux en surnombre",
    "*Peinture de borne-fontaine",
    "*Di - arbre plantation",
    "*Bâtiment - Électricité",
    "Parc - Mobilier - Installation",
    "*SRRR - Modifier plage horaire",
    "*Grands parcs",
    "*Bâtiment - Piscine",
    "*250 - Arrosage illégal",
    "*DI- réparation de bordure",
    "*350 - Occupation du domaine public",
    "*460 - Sécurité bâtiment",
    "*DI - affichage et ornement",
    "*DI - matériels roulants",
    "*Parc - Menuiserie",
    "*Horticulture et entretien - Divers - Bacs à fleurs",
    "*Boîte de service",
    "*Arrêt interdit",
    "Environnement - enseigne",
    "Environnement - autres",
    "*Bancs, poubelles etc",
    "*Bâtiment - Chauffage - Climatisation",
    "*Panier de rue-Réparation/Entretien",
    "*Eau - fuite d'eau côté privé",
    "Permis - Ens. comm. - Affiche temporaire",
    "*DI - parc entretien",
    "*Tonte de gazon",
    "*Parc - Gazon - Terrain vacant",
    "*Permis - Clôture et haie - Clôture non conforme",
    "*Travaux sans permis",
    "*Arbre - Haubanage",
    "*15 - Expulsion chalets, parcs, stationnements",
    "Encaissement - Alarme non-fondée",
    "*Égout Divers - Puisard réparation",
    "*DI - Voirie cas particulier",
    "*Parc - Peinture",
    "Circulation - Travaux majeurs",
    "Immeubles municipaux - Menuiserie",
    "feux-mod. délais et autres changements",
    "*Signalisation écrite",
    "Épandage interdit - Pesticide",
    "*Rôle d'évaluation",
    "*Chalet - Serrurerie",
    "*09 - Porter assistance aux services municipaux",
    "Immeubles municipaux - Alarme",
    "Divers (arr.)",
    "*Parc - Mobilier - Buvette - Fontaine décorative",
    "*Piscine - Extérieure & pataugoire",
    "*Chalet - Chauffage",
    "*Clôtures et haies (nuisances)",
    "*Électricité - Bâtiment municipal",
    "*Obstruction - neige",
    "*Arbre - Nuisance à la signalisation (arrêts et feux de circulation)",
    "*Arrêt / stop lumineux",
    "*Entretien d'édifices municipaux - Métiers",
    "Mobilier urbain - Entretien",
    "*Camion lourd (nuisances)",
    "*Bac brun non remis à l'endroit prévu",
    "*Horticulture - Arbustes - Vivaces (taille, mauv. herbes)",
    "*Chalet - Mobilier",
    "*Parcs - Gazon - tonte VM",
    "*Voirie Travaux Aqueduc",
    "Plomberie - Pataugeoire",
    "Chien sans laisse",
    "*Égout - Puisard - Senteur désagéable",
    "*Permis dépôt domaine public",
    "Voirie - Divers - Surveillance des travaux",
    "*Entretien ménager dans chalet",
    "*260 - Barbecue",
    "*Déchets - Dépôt illégal après inspection - Voirie",
    "*23 - Intervention - Lieu d'accident",
    "Parc - Chalet - Conciergerie et ventilation",
    "Immeubles municipaux - Entretien électrique",
    "*Bâtiment - Peinture",
    "*Morsure - chien",
    "*Don de piano",
    "*Inspection aqueduc",
    "*Graffitis - Bâtiments",
    "*Dir services administratifs",
    "*Parc chalet - Mécanique du bâtiment",
    "*Véhicules non état fonctionnement",
    "*Stèle défectueuse",
    "*Voirie - Travaux Aqueduc",
    "*Patinoires extérieurs",
    "Immeubles municipaux - Entretien général",
    "*Parc - Aménagement - Conception",
    "Immeubles municipaux - Ventilation, climatisation",
    "*tonte de gazon",
    "*E. T. - Entrée charretière",
    "*BI - Entretien",
    "*DI - élagage",
    "Environnement - bruit",
    "*28 - Individus suspects",
    "*420 - Vente",
    "Environnement - insalubrité logement",
    "*360 - Piscine",
    "*Arbre - Haubanage et chirurgie",
    "*Fumier, compost malodorant",
    "Encaissement - Bibliothèque",
    "*Règlement usage de l'eau",
    "*Sports et loisirs - Activités - Activités dans les parcs",
    "*Entrée Charretière - Réalisation",
    "Immeubles municipaux - Panne électrique",
    "*DI - signalisation cas particulier",
    "*neige locale",
    "*Panier de rue",
    "*Neige - Élargissement des rues",
    "*Génie - Pavage - travaux en cours",
    "Haie non réglementaire",
    "*Transit",
    "*DI - compteur d'eau",
    "*Parc mobilier - Dommage par tiers  -VM",
    "Logement - Détérioré, moisi, vermine",
    "*E. T. - Égoût - Puisard - Réparation",
    "*Nuisance à la signalisation",
    "*Permis - Excavation",
    "*Parcs - Éradication VM",
    "Eau - Plomb dans l'eau",
    "*piste cyclable existante",
    "*Égout - Puisard - Problème de rats",
    "*Clôture et haie cour arrière Saint-Léonard",
    "*Parc - Propreté - Entretien aire de jeux",
    "*Neige - Chargement de neige",
    "*Eau - Divers - Remplacer entrée de service en plomb",
    "*Neige - Borne-fontaine",
    "*Neige - Tassement de neige",
    "*DI - élagage parc",
    "*Mandat",
    "*Parc - Aires de jeu",
    "Déchets - Domaine privé à ramasser",
    "*Support à vélo-Réparation/Entretien",
    "*Env.- Bac ou sac de récup.- Dist. - Voirie Transport",
    "*DI - signalisation entretien",
    "*Horticulture - Arrosage VM",
    "*Permis - Construction - Éléments dangereux",
    "*Parc - Appareils de jeux - Bris (danger potentiel)",
    "*Parc - Chalet - vandalisme",
    "Déchets - Illégal - Dépôt - VM",
    "Voirie - Mobilier urbain - Clôture en mailles (frost)",
    "*Surveillance des travaux - Chantier voies cyclables",
    "*Voirie - Coupe de gazon",
    "*BI - Remplacement",
    "*École",
    "*Neige - Signalisation",
    "Voirie - Accumulation d'eau",
    "Voirie - Travaux exécuté par la Ville centre",
    "*Arbre - Abbatage (Travaux recommandé par arboriculteur)",
    "*Agrile",
    "*Génie - Étude refoulement",
    "Bac - Non ramassé",
    "*Surveillance et sécurité publique - Circulation",
    "*Permis - Bruit - Circulation des camions",
    "*Déchets volumineux",
    "*Conseil d'arrondissement - CSLDS",
    "*Génie - Rue - Pavage - Réparation",
    "Voirie - Mobilier urbain - Clôture en bois",
    "*Permis - Bruit - Parcs et espaces publics",
    "Graffitis - Domaine privé - Inspection",
    "*Permis - Zonage - Antenne parabolique",
    "*Direction d'arrondissement - Direction des Travaux publics",
    "Tige de protection non conforme",
    "*Conteneurs à ordures",
    "Signalisation - Travaux majeurs",
    "*Inspection et dératisation",
    "*Nettoyage (arr.)",
    "*Règlement salubrité entretien et logement",
    "Enseignes amovibles",
    "*Équipement récréatif",
    "300 - Sinistre",
    "*Parc - Vandalisme - Graffitis",
    "*Parc - Aménagement clôture",
    "Entretien d'édifices municipaux - Demande culture CSLDS",
    "*Arbustes, vivaces",
    "*Entretien d'édifices municipaux - Mécanique du bâtiment",
    "*Parc - Activité hivernale - Ski de fond",
    "*Équipement de jeu - vandalisme, bris",
    "*Di - arbre essouchement",
    "Marquage à contrat",
    "*Modification à la signalisation",
    "Environnement - herbe longue",
    "Parc - Mobilier - Entretien",
    "*Asphalte permanent",
    "Bac - Divers",
    "*Nettoyage domaine public",
    "*ÉLU - Direction AUP",
    "Environnement - abri d'auto",
    "*EG - Regard réparation mineure",
    "*Horticulture et entretien - fleurs",
    "*Neige - Permis de dépôt de neige REFUSÉ",
    "*Projection de lumière (nuisances)",
    "*Permis - Autre type d'abri temporaire",
    "*Extermination - Autre",
    "*WOONERF",
    "*E. T. - Feux piétons",
    "*Tige de protection",
    "*Mobilier de parc (entretien)",
    "*Ent - Edif.mun. - Graffitis - Édif public - Mairie, Serv. Techniques, Station pompage, Signalisation",
    "*Bureau Accès divers info",
    "*Direction d'arrondissement - CSLDS",
    "*Borne-fontaine - Entretien - Voirie",
    "*DI - borne d'incendie",
    "*E. T. - Pavé uni - Réparation",
    "*Génie - Réparation arrière trottoir",
    "Constat d'infraction - Neige",
    "NE Plus Utilisé - Bac de MO sorti en temps prohibé",
    "Voirie - Affichage extérieur",
    "Voies cyclables - Entretien",
    "*Neige - Passage piétonnier",
    "*Déneigement chalet,sentier,immeuble",
    "*Neige - Borne fontaine",
    "*Éclairage - entretien - Parc et terrain Sportif",
    "Égout - Puisard gelé",
    "Aménagement urbain et service aux entreprises",
    "*E. T. - Géomatique",
    "Logement - Toiture qui coule",
    "*Sentiers",
    "*E. T. - Rues piétonnes",
    "Environnement - entretien/délabrement bâtiment",
    "*Antenne parabolique",
    "*Panneau publicitaire",
    "*Arbre - Nuisance à la signalisation (autre qu'arrêt et feux de circulation)",
    "*Parc - Gazon Réparation",
    "Mobilier urbain - Abribus nettoyage",
    "Immeubles municipaux - Mobilier réparation et fabrication",
    "*Piétons",
    "Environnement - animaux",
    "*Drain puisard (arr,)",
    "Pavé uni",
    "Ferm. d'une conduite d'eau -urgente (arr.)",
    "*Bruit à l'intérieur",
    "*Déchets-Collecte-bris",
    "*Permis - Construction - Zonage",
    "Permis - Cabanon",
    "*Info-travaux - Réparation mineure - voirie",
    "*Limiteur de vitesse - Rue",
    "*Ent - Edif.mun. - Graffitis - Édif public - Infrastructure, Voirie",
    "*Jardins Communautaires",
    "*Mobilier de parc (nouveau)",
    "Oriflamme",
    "Égouts - Infiltration",
    "*Affichage - Nuisible",
    "bac brun endommagé, perdu, volé",
    "*Parc du Mont-Royal - Lac au Castor",
    "*Parc - Aménagement - Études préliminaires",
    "*Borne d'incendie à déneiger",
    "*Arbre - Empiettement sur domaine privé VM",
    "Environnement - Collecte des résidus alimentaires - Bac livraison",
    "Autorisation - Pesticide",
    "*Demande de renseignement - signalisation permanente",
    "*Parc - Terrains - sportifs - Soccer",
    "*Terrasses temporaires",
    "*Pesticide - Délation d'utilisation",
    "bac brun distribution",
    "Éclairage - Travaux majeurs",
    "*Voirie - Trottoir - Compilation",
    "Logement - Sans chauffage, ni eau, ni équip. sanitaire",
    "Immeubles municipaux - Drapeau et pavoisement",
    "Bac - Modification de volume",
    "*Gazon - Réparation",
    "*Matériaux de construction VM",
    "*Eau Divers - Coupe privées - Facturation",
    "Voirie - Pavage - Réparation - Près d'un puisard ou trou d'homme",
    "*Feux de circulation - Études",
    "*Nivellement baseball",
    "*Arbre - Abattage d'arbre - À revoir",
    "Permis - Divers - Antenne parabolique - Inspection",
    "*Fuite à la conduite",
    "bac brun modification volume",
    "*Parc - Chalet bris (électriques, plomberies, vitres etc)",
    "*Tonte tour d'arbre",
    "*DI - réparation d'aqueduc",
    "Immeubles municipaux - Téléphonie, réseau et caméra",
    "*Permis Vente et consommation d'alcool S et L",
    "*Égout - Réparation - Entretien",
    "*Réparation de chambre de vanne",
    "*Di - qualité de l'air intérieur des bâtiments municipaux",
    "*Génie - Trottoir - travaux planifiés",
    "*Pesticide - délation d'utilisation",
    "Environnement - Collecte des résidus alimentaires - Non ramassée",
    "AUSE - Neige",
    "Environnement - haie hauteur",
    "*Mesures de mitigation travaux",
    "*Horticulture - Fleurs annuelles aménagement",
    "*Voirie - Mauvaises herbes terrain public - inspection",
    "*Arbre - Demande d'information concernant arbre publc",
    "*Wi-Fi",
    "*Égout - Nettoyage - Contrat",
    "*Plantation d'arbre privé",
    "*Parc - Aménagement - Ajout d'équipement",
    "*Réseau artériel",
    "*Conteneur de dons",
    "Entrée charretière - Exécution",
    "*Planification des travaux - Études voies cyclables",
    "Immeubles municipaux - Abeilles, guêpes, bourdons à l'intérieur",
    "*Réparation et remplacement de services",
    "*Qui alimente quoi",
    "*Neige - Stationnement municipal",
    "*Programme Muralité - PMR",
    "Déchets - Poubelles municipales",
    "Chien dangereux",
    "*Piscine - Intérieure",
    "*Branche accrochée",
    "Arbre - Maladie et insectes - Domaine privé - permis pour pesticides",
    "Immeubles municipaux - Peinture",
    "RETOUR - SITE",
    "*Banc-Réparation/Entretien",
    "*Conseil d'arrondissement - Dir.Arr.",
    "*Reconnaissance",
    "*Greffe et communications",
    "*Stationnement à angle",
    "*Vignette de stationnement - Blaise et Closse",
    "*Parc - Aménagement - Exécution",
    "*Borne-fontaine - Déplacement - Ét.Tech.",
    "*Bibliothèque NDG",
    "Voirie - Divers - Gestion Retour DDS",
    "*Arbres de parc",
    "*Herbe à poux",
    "*Égout Divers - Regard réparation",
    "Gazon et mauvaises herbes - Demande CSLDS",
    "*Éclairage de parc",
    "Varia - Demande CSLDS",
    "*Fuite base de borne-fontaine",
    "*Abattage d'arbre - terrain public",
    "*Déneigement sans permis",
    "*Permis - Excavation PDDP",
    "*Sports et loisirs - Partenaires",
    "*Permis - Divers - Lotissement",
    "*E. T. - Arrêt interdit",
    "*Neige - Divers - Borne Fontaine",
    "*Déversement (nuisances)",
    "*Réparation de conduite d'égouts",
    "*Fuite réparation et rempl. de services",
    "Boîte de service à niveler",
    "*Voirie - EC - Modification",
    "Arbre - Empiettement sur domaine public VM",
    "*Direction d'arrondissement-Aménagement Urbain et services aux entreprises",
    "*Enseigne et signalisation",
    "*Occupation permanente du domaine public",
    "*Bibliothèque BIC",
    "Transport de mobilier - Prêt d'équipement",
    "Odeur désagréable",
    "*Voie réservée autobus",
    "*Sports et loisirs - Centre communautaire",
    "Signalisation temporaire - Installation et ou prêt",
    "*Poteaux ou lampadaires-Retrait ou déplacement",
    "Parc demande interne divers",
    "*Entretien d'édifices municipaux - Ventilation, climatisation, chauffage",
    "Bruit - Thermopompe, appareil de climatisation",
    "Arbre - Varia - Enlèvement de branches",
    "*Horticulture - Arbustes - Vivaces aménagement",
    "E.T. Aménagement nouveau parc VM",
    "Odeurs lacs",
    "*Enseignes Portatives",
    "Immeubles municipaux - Soudure",
    "*Vermine, insectes nuisibles",
    "Parc - Chalet - Entretien et réparation",
    "*Parcs - Restauration VM",
    "*Eau Divers - Disjonction de branchement d'eau",
    "*Jeu d'adulte",
    "*Terrains vacants-mauvais herbes",
    "*Arbres de ruelle",
    "Éclairage aveuglant",
    "Défense de jeter des déchets",
    "*Conseil d'arrondissement - Serv.admin.",
    "*Objets suspendus sur fils électriques",
    "*Culture - Installations - Centre culturel",
    "Immeubles municipaux - Chauffage à eau chaude",
    "Ruelle verte",
    "Permis - Logement - Fuite d'eau privée",
    "Déneigeur privé - Poteau",
    "Tige de protection (2018)",
    "*Plan de transport",
    "*Arénas",
    "Collecte de paniers de rue",
    "*Feuilles mortes dans parc",
    "Éclairage existant - entretien mineur",
    "Déneigeur privé - Permis",
    "*transport",
    "*E. T. - Camionnage",
    "*EG - Regard réparation majeure",
    "Horticulture - Varia - Pesticide - Vérification infestation",
    "E.T. Ajout nouveaux équipements VM",
    "Transport et Livraison",
    "Environnement - odeur",
    "*Plantation exécution",
    "Immeubles municipaux - Chauffage à air chaud",
    "Transport",
    "gazon réparation dommage neige",
    "Environnement - débris voie publique",
    "Immeubles municipaux - Chauffage électrique",
    "*Graffitis Voirie - Mobilier Urbain",
    "Evénement",
    "Pelouse - mauvaises herbes",
    "fête des voisins",
    "Tuyauterie gelée(arr.)",
    "Parc - Chalet - Electricité",
    "*Souches, tronc et branche de + 20 cm de diamètre à ramasser",
    "*Parc - Propreté - Entretien carré de sable",
    "Trottoir ou bordure - Réparation  RMT",
    "Permis - Abattage d'arbre sur terrain privé",
    "Immeubles municipaux - Affichage",
    "*Bac résidus verts - Demande de bac supplémentaire",
    "*Bac résidus verts - Remplacement (volé ou cuve brisée)",
    "*Travaux de béton rue",
    "*Aménagement Chaumont",
    "Construction - clôture",
    "Environnement - matières dangereuses",
    "Environnement - eau/égout",
    "*Feu ou lampadaire - Retrait ou ajout",
    "*Bris dans chalet",
    "*Fourniture d'équipement évén. spéciaux",
    "permis de construction et transformation",
    "Env. - Graffitis - Édif public - Autres bâtiments, Équipements et Infrastructure de Loisirs",
    "Environnement - neige",
    "Affichage sauvage",
    "Déneigeur privé - Enseigne",
    "*Demande agent tech.ing.municipal",
    "Mobilier urbain - Transport",
    "*Extermination guêpes",
    "*Demande de filtre - Entrée de service en plomb",
    "*Fourniture de service évén. spéciaux",
    "Égout - Divers - Réseau secondaire d'égout - Inspection",
    "*Parcojours",
    "*Voirie - EC - Nouvelle construction",
    "*Parc - Aménagement - Réalisation",
    "REM - Occupation permanente",
    "Éclairage existant - entretien majeur",
    "Environnement - véhicule non autorisé",
    "*Conseil d'arrondissement - Bureau technique",
    "Environnement - stationnement",
    "**Centre des loisirs - Remboursement d'activité",
    "Puisard/TH-Couvercle Affaissement",
    "Modules de jeux",
    "Eau - Divers",
    "Terrain sportif - Demande CSLDS",
    "*ÉLU - Direction d'arrondissement",
    "*Piétonnisation - Masson",
    "Puceron du tilleul",
    "GMR -  Nouvelle implantation",
    "Éclairage - Demande CSLDS",
    "Appropriation citoyenne",
    "Propreté - Demande CSLDS",
    "Favorable - Modification",
    "Bixi",
    "*Demande de propriété",
    "Entrave - Piste cyclable",
    "*Bibliothèque CDN",
    "Info-travaux - Urgence",
    "*Dépôt illégal - Ramassage",
    "*Partenaires",
    "Extermination - Guêpes",
    "Boite de service à mettre en ordre",
    "Travaux Publics - RDD",
    "Fuite boîte-maison",
    "*Débarcadère - Handicapé",
    "Borne fontaine - Obstruction",
    "*Contrôle du stationnement voie publique",
    "Égout - Divers - Tuyau de service d'égout - Raccordement croisé",
    "*Équipement terr. sportifs",
    "Fuite service",
    "Dos d'âne - Ruelle",
    "*Occupation - Divers",
    "*Occupation sans permis",
    "*Signalisation - Règlement",
    "**Stationnement - Handicapé",
    "*Débarcadère - Autobus",
    "Travaux Publics - Recyclage",
    "Signalisation cachée par des végétaux - Avis",
    "Voirie - Nettoyage des fossés",
    "Réparation d'entrée charretière existante",
    "Clôture et haies (local)",
    "Voirie - Mauvaise herbe bordure",
    "Voirie - Accident ou déversement",
    "Boite de service à niveler",
    "Contrôle animalier - domaine public",
    "*Retour de DDS - en attente",
    "*Dos d'ane Rues et Ruelles-Entretien",
    "Responsable soutien aux élus",
    "Demande d'information sur l'agrile du frêne - Arbre privé",
    "*Inspection de borne fontaine",
    "Nettoyage de puisards - rue",
    "Électricité-évènement",
    "*Égout Divers - Egout-Murage de branchement d'égoût",
    "Affaires - Info",
    "Voirie - Nettoyage sites récupération",
    "Sports et loisirs - Installations - Terrains sportifs extérieurs",
    "Sports et loisirs - Installation - Auditorium",
    "Sports et loisirs - Installations - Centres communautaires",
    "Compteur ICI Entretien",
    "Refuge - Propreté",
    "*Puisard/TH-Refoulement/Débordement/Blocage/Clés",
    "*Puisard/TH-Couvercle Abs./Brisé/Déplacé/Affaissement",
    "TEST-ANALYSE-SO",
    "Bac de déchets - Modification de volume",
    "Voirie -Dégagement de fossé",
    "Voirie - Nettoyage de mail central",
    "Nettoyage de puisards - ruelle",
    "Bac de MO - Livraison",
    "Santé",
    "Dépôt neige-ruelle",
    "Bac roulant - Ramassage du bac",
    "Bac de MO - Modification de volume",
    "Sports et loisirs - Installations - Jardins communautaires",
    "Modifications parcours de balai",
    "Réparation de puisards - ruelle",
    "Réparation de puisard - rue",
] as const;